language: node_js
node_js:
- 0.10
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- ./node_modules/protractor/bin/webdriver-manager update
- ./node_modules/protractor/bin/webdriver-manager start
- sleep 3
script:
- "lineman spec-ci"
- "lineman grunt spec-e2e"
